### ISSUE TITLE
The title screen is literally empty

### ISSUE THREAD

**Issue by TheDarkKnight69** [NT-Bourgeois-Iridescence-Technologies/Project-Raven#4]
**Describe the bug**
I'm on PPSSPP, a stable PSP emulator. When I try to start the game it goes on the title screen but then the placeholders for "singleplayer" stuff like that is empty. I do not know if I messed up something, I extracted the zip file to the place where I keep my games.
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/91176991/152739438-c6d88456-44ae-43d0-8659-f988831d58ee.png)

**Additional context**

**Comment by IridescentRose** [comment]
PPSSPP does not have valid *.pgf files for the purpose of the application. Regardless, the most up to date project series is at: https://github.com/CrossCraft/CrossCraft-Classic
